# Dependencies
markdown: kramdown
highlighter: rouge

title: Jason Thai
# description: Jason's personal site

author:
  name: Jason Thai

paginate:         5
# paginate_path:    '/page:num'
                    # Or '/blog/page:num' if you want to move your index pages
disqus:
  shortname: jasontrithai


plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate

sidebar_home_link: true