# Dependencies
markdown: kramdown
# highlighter: rouge

# remote_theme: fongandrew/hydeout
theme: minima
email: thaixtri@gmail.com
title: Blog of Things
description: Jason Thai's personal page
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://jasonthai.me" # the base hostname & protocol for your site, e.g. http://example.com
author: Jason
# author:
  # name: Jason Thai

# paginate:         5
# paginate_path:    '/page/:num'
pagination:
  enabled: true
  debug: true
  per_page: 5
  permalink: '/page/:num/'
  limit: 0
  sort_field: 'date'
  sort_reverse: true

header_pages:
  - about.md
  - posts.md
  - tags.html
  - visited-places.md

disqus:
  shortname: jasons-1

github_username: zirius
linkedin_username: jasontthai

show_excerpts: true
excerpt_separator: <!-- more -->

ads_enable: false

permalink: /blog/:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "_posts"
      type: "posts"
    values:
      category: "en"
  -
    scope:
      path: "_posts/vi"
      type: "posts"
    values:
      category: "vi"

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate-v2
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-avatar
  - jekyll-redirect-from
  - jekyll-admin

# sidebar_home_link: true

google_analytics: UA-120912817-1
