# Dependencies
markdown: kramdown
highlighter: rouge

remote_theme: fongandrew/hydeout
# theme: jekyll-theme-hydeout
title: Jason Thai
# description: Jason's personal site

author:
  name: Jason Thai

paginate:         5
# paginate_path:    '/page:num'
                    # Or '/blog/page:num' if you want to move your index pages
disqus:
  shortname: jasons-1


plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate

sidebar_home_link: true