# Dependencies
markdown: kramdown
# highlighter: rouge

# remote_theme: fongandrew/hydeout
theme: minima
email: thaixtri@gmail.com
title: Blog of Things
description: Jason Thai's personal page
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://jtthai.com" # the base hostname & protocol for your site, e.g. http://example.com

# author:
  # name: Jason Thai

# paginate:         5
# paginate_path:    '/page:num'
                    # Or '/blog/page:num' if you want to move your index pages
disqus:
  shortname: jasons-1

minima:
  social_links:
    github: zirius
    facebook: zirius

show_excerpts: true

permalink: /blog/:year/:month/:day/:title/

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-avatar
  - jekyll-redirect-from
  - jekyll-admin

# sidebar_home_link: true

google_analytics: UA-120912817-1