version: 2
jobs:
  deploy:
    branches:
      only:
        - develop
    docker:
      - image: circleci/ruby:2.4.3-node-browsers
        environment:
          USER_NAME: zirius
          USER_EMAIL: thaixtri@gmail.com
    steps:
      - checkout
      - run: npm install
      - run: bundle install
      - run: JEKYLL_ENV=production bundle exec jekyll build
      - deploy:
          name: Deploy Release to GitHub
          command: |
            if [ $CIRCLE_BRANCH == 'develop' ]; then
              bash .circleci/setup-github.sh
            fi
workflows:
  version: 2
  build:
    jobs:
      - deploy